# Generated by Django 6.1 on 2026-08-07 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('harassment', 'Harassment'), ('theft', 'Theft'), ('lighting', 'Poor lighting'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('location_lat', models.FloatField()),
                ('location_lng', models.FloatField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewed', 'Reviewed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_reports', to='accounts.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SafetyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('area_lat', models.FloatField()),
                ('area_lng', models.FloatField()),
                ('radius_km', models.FloatField(default=1.0)),
                ('active_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_alerts', to='accounts.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
