# Generated by Django 5.1.4 on 2026-08-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='is_anonymous',
            field=models.BooleanField(default=False, help_text="If true, the reporter's identity should not be shown in Community UI, even though the FK is kept for moderation/abuse purposes."),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='category',
            field=models.CharField(choices=[('harassment', 'Harassment'), ('stalking', 'Stalking'), ('theft', 'Theft'), ('unsafe_area', 'Unsafe area'), ('other', 'Other')], max_length=20),
        ),
    ]
