# Generated by Django 5.1.4 on 2026-08-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_incidentreport_is_anonymous_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='category',
            field=models.CharField(choices=[('harassment', 'Harassment'), ('stalking', 'Stalking'), ('theft', 'Theft'), ('unsafe_area', 'Unsafe area'), ('tip', 'Safety tip'), ('question', 'Question'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='location_lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='location_lng',
            field=models.FloatField(default=0.0),
        ),
    ]
