# Generated by Django 6.1 on 2026-08-07 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourneySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_point', models.CharField(max_length=255)),
                ('end_point', models.CharField(max_length=255)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('was_completed_safely', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_summaries', to='accounts.profile')),
            ],
            options={
                'ordering': ['-ended_at'],
            },
        ),
    ]
